### ISSUE TITLE
nsa out of my browser!

### ISSUE THREAD

**Issue by lawnsea** [pxon/pxon.github.io#1]
<img width="371" alt="screenshot 2015-12-04 17 21 41" src="https://cloud.githubusercontent.com/assets/296238/11603939/021c95f0-9aac-11e5-811b-0e0cc98b2abf.png">

**Comment by jennschiffer** [comment]
can't replicate WONTFIX

**Comment by fivetanley** [comment]
WAKE UP SHEEPLE
